" make jk do esc
inoremap jk <Esc>
inoremap pdb import pdb; pdb.set_trace()

" shortcuts for tabs
nnoremap tn :tabnew<Space>
nnoremap tk :tabnext<CR>
nnoremap tj :tabprev<CR>
nnoremap th :tabfirst<CR>
nnoremap tl :tablast<CR>

" backspace working as usual
nnoremap <bs> X
set backspace=indent,eol,start " backspace working as usual in insert mode

set clipboard=unnamedplus " enables copying into os clipboard
set mouse=a " enables mouse
"set ruler " enables curser position

" Show all untanted trailing whitespace
" MUST be inserted before colorscheme command
highlight ExtraWhitespace ctermbg=red guibg=red
autocmd ColorScheme * highlight ExtraWhitespace ctermbg=red guibg=red
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/

" Highlight tabs
set list
set listchars=tab:▸·

colorscheme default " colors
syntax on " Switch Syntax highlighting on
" set syntax to jinja for all html files
au BufNewFile,BufRead *.html set syntax=htmljinja
set number " Show line number

set tabstop=4 " number of visual spaces per TAB
set softtabstop=4 " number deleted by pressing backspace
set shiftwidth=4 " should be the same as softtabstop
set textwidth=120 " Maximal textwidth
set autoindent " continue with upper indentation
set expandtab " tabs are spaces

" for html/js, 2 spaces
autocmd Filetype html setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab
autocmd Filetype htmldjango setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab
autocmd Filetype css setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab
autocmd Filetype javascript setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab

set hlsearch " highlight matches
set ignorecase smartcase " ignores cases for search function
set shortmess-=S " show count of search hits
set incsearch " see search results as you type

" Search down into subfolders
" Provides tab-completion for all file relad tasks
set path+=**

" Display all matching commands/files when we tab complete
set wildmenu

" easier moving/indentation of blocks
vnoremap < <gv
vnoremap > >gv

" ctrl-x ctrl-o completion
set omnifunc=syntaxcomplete#Complete

" LaTeX commands
" Add file my_bibliography.bib in same folder as my_file.tex
" Add to my_file.tex header:
"   \usepackage[backend=biber]{biblatex}
"   \addbibresource{my_bibliography.bib}
" Add if non-cited files should be included
"   \nocite{*} or \nocite{<bibkey>}
" Print bibliography with
"   \printbibliography
" Correct command ordering:
"   1. pdflatex my_file.tex
"   2. pdflatex my_file.tex
"   3. biber my_file
"   4. pdflatex my_file.tex
" pdflatex my_file.tex
map <f2> :w<CR>:! pdflatex %<CR><CR>
" Open my_file.pdf
map <f3> :! xdg-open %:r.pdf & disown<CR><CR>
" biber my_file
map <f4> :w<CR>:! biber %:r<CR><CR>
" Full command list:
map <f5> <f2><f2><f4><f2><f3>

" Spell check
map <f6> :setlocal spell! spelllang=en_us<CR>
map <f7> :set spelllang=de<CR>
autocmd Filetype tex setlocal spell! spelllang=en_us,de
