#!/bin/bash

THIS_SCRIPT=$(realpath $0)
THIS_SCRIPT_DIR=$(dirname $THIS_SCRIPT)
CONFIG_DIR=$(dirname $THIS_SCRIPT)'/config'

# Look for updates.
git -C $THIS_SCRIPT_DIR pull

# Files and dirs to sync.
SYNC_FILES=$(find $CONFIG_DIR -mindepth 1 -type f)
SYNC_DIRS=$(find $CONFIG_DIR -mindepth 1 -type d)

# Target dirs containing symbolic links.
HOME_DIRS=$(echo "$SYNC_DIRS" | sed "s|^$CONFIG_DIR|$HOME|")

# Create all dirs in home dir if they do not exist.
mkdir -p $HOME_DIRS

# Create symbolic links for all files
for f in $SYNC_FILES;
do
  f_ln=$(echo "$f" | sed "s|^$CONFIG_DIR|$HOME|")
  # Removes symbolic links if they exist.
  if [ -L $f_ln ]
    then
        rm $f_ln
  fi
  ln -sv $f $f_ln
done;

# Create symbolic links for this script in ~/bin.
THIS_SCRIPT_LN=$HOME/bin/$(basename $THIS_SCRIPT)
if [ -L $THIS_SCRIPT_LN ]
  then
    rm $THIS_SCRIPT_LN
fi
ln -sv $THIS_SCRIPT $THIS_SCRIPT_LN

# push to GitHub
git -C $THIS_SCRIPT_DIR add -A
git -C $THIS_SCRIPT_DIR commit -m "New backup $(date +'%Y-%m-%d %H:%M:%S')"
git -C $THIS_SCRIPT_DIR push origin main
